# Generated by Django 4.0.3 on 2022-04-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_customer_remove_shippinginfo_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
